# Site settings
title: Arabic Design Tool
email: dev@ocupop.com
baseurl: ""
permalink: pretty

# Social sharing
description:
socialshare:
  featured_image: assets/img/socialshare.png
  twitter:
    username:
    image:

collections:
  principles:
    output: true
  tools:
    output: true
  posts:
    output: true


# Google Analytics
analytics_code:

# Build settings
safe: false
sass:
  # style: compressed
  sass_dir: _scss


# Localization
languages: ["ar", "en"]
default_lang: ar
exclude_from_localizations: ["assets", "js"]


placeholder_image: https://via.placeholder.com/1000x1000/333333/000000?text=Placeholder