# Site settings
title: Arabic Design Tool
email: dev@ocupop.com
baseurl: ""
permalink: pretty

# Social sharing
description:
socialshare:
  featured_image: assets/img/socialshare.png
  twitter:
    username:
    image:

collections:
  principles:
    output: true
  tools:
    output: true
  posts:
    output: true

defaults:
  - scope:
      path: ""
      type: "tools"
    values:
      layout: "tool"


# Google Analytics
analytics_code:

# Build settings
safe: false
sass:
  # style: compressed
  sass_dir: _scss


# Localization
languages: ["ar", "en"]
default_lang: ar
exclude_from_localizations: ["assets", "js"]


placeholder_image: https://via.placeholder.com/1200x900/000/222?text=placeholder

_options:
  some_markdown:
    format: p h1 h2 h3 h4 h5 h6 pre address div
    bold: true
    italic: true
    numberedlist: true
    code: true
    table: true
    left: text-left
    center: text-center
    right: text-right
    image: true
    embed: true
  _block:
    format: p h1 h2 h3 h4 h5 h6 pre address div
    bold: true
    italic: true
    numberedlist: true
    code: true
    table: true
    left: text-left
    center: text-center
    right: text-right
    image: true
    embed: true
  content:
    undo: true
    redo: true
    format: p h1 h2 h3 h4 h5 h6 pre address div
    bold: true
    italic: true
    numberedlist: true
    code: true
    table: true
    left: text-left
    center: text-center
    right: text-right
    image: true
    embed: true